// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qternzuufanuxcfbypsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0ZXJuenV1ZmFudXhjZmJ5cHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzA5MzcsImV4cCI6MjA3MTQ0NjkzN30.jDqT0t9m0l93xwWCxvuW4tUuZVSgFKvooxTHNm7UXHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});